import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useBackground } from '../context/BackgroundContext'

export default function Home() {
  const { setBackground } = useBackground()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main onMouseEnter={() => setBackground(true)} onMouseLeave={() => setBackground(false)} style={{position:'relative', zIndex:'10'}}>asdf</main>
    </div>
  )
}
